AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Weather API Server
Parameters:
  DarkSkyAPIKey:
    Type: String
  CorsDomain:
    Type: String
Globals:
  Api:
    MethodSettings:
      - ResourcePath: "/*"
        HttpMethod: "*"
        ThrottlingBurstLimit: 5
        ThrottlingRateLimit: 10

Resources:
  WeatherFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../dist
      Handler: index.handler
      Runtime: nodejs10.x
      MemorySize: 128
      Timeout: 30 # seconds, 300 max
      Environment:
        Variables:
          CORS_DOMAIN: !Ref CorsDomain
          DARK_SKY_API_KEY: !Ref DarkSkyAPIKey
      Events:
        WeatherApi:
          Type: Api
          Properties:
            Path: /weather
            Method: GET
