AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Weather API Server
Parameters:
  DarkSkyAPIKey:
    Type: String
Resources:
  WeatherFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../dist
      Handler: index.handler
      Runtime: nodejs8.10
      MemorySize: 128
      Timeout: 30 # seconds, 300 max
      Environment:
        Variables:
          DARK_SKY_API_KEY: !Ref DarkSkyAPIKey
      Events:
        WeatherApi:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: GET
